### ISSUE TITLE
Comiling pgSentinel to non standard path for pgsql

### ISSUE THREAD

**Issue by ojo77** [pgsentinel/pgsentinel#10]
I compiled PGSQL in a non standard place using configure :

```
./configure --prefix=/software/postgresql/v10.4 
```

When trying to make pgSentinel it throws the following error :
```
/software/postgresql/pgsentinel-master/src$ make
Makefile:19: /usr/lib64/pgsql/pgxs/src/makefiles/pgxs.mk: No such file or directory
make: *** No rule to make target `/usr/lib64/pgsql/pgxs/src/makefiles/pgxs.mk'.  Stop.
```

As a workaround I used symbolic links

```
ln -s /software/postgresql/v10.4/lib /usr/lib64/pgsql
ln -s /software/postgresql/v10.4/include /usr/include/pgsql
```

When installing it of course placed the binaries in standard emplacements
```
 make install
/bin/mkdir -p '/usr/lib64/pgsql'
/bin/mkdir -p '/usr/share/pgsql/extension'
/bin/mkdir -p '/usr/share/pgsql/extension'
/bin/install -c -m 755  pgsentinel.so '/usr/lib64/pgsql/pgsentinel.so'
/bin/install -c -m 644 .//pgsentinel.control '/usr/share/pgsql/extension/'
/bin/install -c -m 644 .//pgsentinel--1.0b.sql  '/usr/share/pgsql/extension/'
```

I had to move /usr/share/pgsql/extension/* to /software/postgresql/v10.4/extension/* in order to make it work

Is it possible to have a "configure" tool to be able to install pgsentinel directly to non standards locations ?

Thank you
Olivier

**Comment by ckikof** [comment]
Hello Olivier,

we'll have a look and keep you informed

Christophe

**Comment by pgsentinel** [comment]
Hello Olivier,

I compiled only on non standards location without any issues:

make install
/bin/mkdir -p '/usr/local/pgsql10/lib'
/bin/mkdir -p '/usr/local/pgsql10/share/extension'
/bin/mkdir -p '/usr/local/pgsql10/share/extension'
/usr/bin/install -c -m 755  pgsentinel.so '/usr/local/pgsql10/lib/pgsentinel.so'
/usr/bin/install -c -m 644 .//pgsentinel.control '/usr/local/pgsql10/share/extension/'
/usr/bin/install -c -m 644 .//pgsentinel--1.0b.sql  '/usr/local/pgsql10/share/extension/'

Does "which pg_config" output the right location? 

In my case:

which pg_config
/usr/local/pgsql10/bin/pg_config
 
Should be /software/postgresql/v10.4/bin/pg_config in your case.

If not, update the PATH variable and give a new try.

Thx

**Comment by ckikof** [comment]
OK, i close it.
