### ISSUE TITLE
modify pgsentinel_ash.max_entries

### ISSUE THREAD

**Issue by xunyu110** [pgsentinel/pgsentinel#17]
when i modify   pgsentinel_ash.max_entries to 100000.

database crash.

log:

### 2018-08-09 11:36:07.040 CST [17172] FATAL:  not enough shared memory for data structure "Ash Entry Array" (19200000 bytes requested)

what is the problem？

**Comment by bdrouvot** [comment]
How much memory do you have on your machine? If possible, could you try to increase it and give it a new try?

**Comment by xunyu110** [comment]
The memory is 32G.
  free   -m          
                    total        used        free      shared  buff/cache   available
Mem:          32011         827         183       12566       31000       18144
Swap:          3967         613        3354

If I need to store a week's worth of data in a table instead of memory, what settings do I need to modify? Or how to modify the source code?

**Comment by bdrouvot** [comment]
Your machine had not enough free shared memory when you got the error.

My machine has 8GB:

```
pgu:~$ grep MemTotal /proc/meminfo
MemTotal:        7973940 kB
```

and I can set up 100 000 ash entries:

```
pgu:~$ psql -c "SELECT setting FROM pg_settings WHERE name='pgsentinel_ash.max_entries';"
 setting
---------
 100000
(1 row)
```
and up to 2 000 000:

```
pgu:~$ psql -c "SELECT setting FROM pg_settings WHERE name='pgsentinel_ash.max_entries';"
 setting
---------
 2000000
(1 row)
```

The memory needed for an ash entry needs to be optimized (an issue will be opened for that).

The extension does not provide the ability to store the entries into a table. 
To store the entries into a table, you could create your own pulling of pg_active_session_history into a table (say one time per day, and put max entries high enough for one day).
