### ISSUE TITLE
waiting for lock session doesn't provide queryid, query nor cmdtype

### ISSUE THREAD

**Issue by legrandlegrand** [pgsentinel/pgsentinel#19]
Hello,
when playing with pgsentinel (thanks for that very usefull tool !),
I see that queryid, query and cmdtype are not populated for session waiting for lock (top_level_query is correct).

This prevents from joining pg_active_session_history with pg_stat_statements on queryid ;o(
Could this be changed ?

Merci d'avance
Salutations
PAscal

test case from psql:
**session 1:**
create table tt (id int);
insert into tt values (1);
begin;
delete from tt;

**session 2:**
update tt set id=id+1;

**Comment by legrandlegrand** [comment]
Strange ...
I know that SQL entries are not in pg_stat_statements until they finish.

This is not only for queries waiting for locks,   but for any long one.

For exemple, "sélect pg_sleep(10)", is visible  in  pg_active_session_history ( with query, queryid,cmdtype), and not in pg_stat_statements before its end.

Regards
PAscal

**Comment by legrandlegrand** [comment]
For information,
I posted that question in postgres forum
https://www.postgresql-archive.org/no-queryId-in-post-parse-analyze-hook-when-row-is-locked-td6054044.html (with no answer yet)

and tested pg_wait_sampling
https://github.com/postgrespro/pg_wait_sampling
that works with the same test case (pg11).
That program is very similar to pgsentinel but is not using the same hook
planner_hook (and not post_parse_analyze_hook) ...

Maybe this is a Postgres Bug or a pgsentinel one, but it is one, and should be categorized accordingly.
You can always close it too.

Regards
PAscal

**Comment by bdrouvot** [comment]
I'll have a look, thanks for the update.

**Comment by legrandlegrand** [comment]
Root cause is that there is a test on blockers (see pgsentinel.c)

		// query
		if (AshEntryArray[i].query[0] != '\0' && !Int32GetDatum(AshEntryArray[i].blockers))
			values[j++] = CStringGetTextDatum(AshEntryArray[i].query);
		else
			nulls[j++] = true;

		// cmdtype
		if (AshEntryArray[i].cmdtype[0] != '\0' && !Int32GetDatum(AshEntryArray[i].blockers))
                        values[j++] = CStringGetTextDatum(AshEntryArray[i].cmdtype);
		else
                        nulls[j++] = true;

		// query_id
		if (!Int32GetDatum(AshEntryArray[i].blockers))
			values[j++] = Int64GetDatum(AshEntryArray[i].queryid);
		else
			nulls[j++] = true;

my previous proposal was only a workarround ...
Regards
PAscal

**Comment by legrandlegrand** [comment]
proposed fix:

		// query
//old		if (AshEntryArray[i].query[0] != '\0' && !Int32GetDatum(AshEntryArray[i].blockers))
		if (AshEntryArray[i].query[0] != '\0')
			values[j++] = CStringGetTextDatum(AshEntryArray[i].query);
		else
			nulls[j++] = true;

		// cmdtype
//old		if (AshEntryArray[i].cmdtype[0] != '\0' && !Int32GetDatum(AshEntryArray[i].blockers))
		if (AshEntryArray[i].cmdtype[0] != '\0')
                        values[j++] = CStringGetTextDatum(AshEntryArray[i].cmdtype);
		else
                        nulls[j++] = true;

		// query_id
//old		if (!Int32GetDatum(AshEntryArray[i].blockers))
		if (AshEntryArray[i].queryid)
			values[j++] = Int64GetDatum(AshEntryArray[i].queryid);
		else
			nulls[j++] = true;

**Comment by bdrouvot** [comment]
sorry for the delay, will take care of it.

**Comment by bdrouvot** [comment]
implemented
