### ISSUE TITLE
Release schedule for stabilized version.

### ISSUE THREAD

**Issue by kayform** [pgsentinel/pgsentinel#21]
hello

Thanks for that very usefull tool for me
I wonder when PGSENTINEL will be released officially.
As you know, the extension of postgresql can be a big impact on the service.

Regards

**Comment by bdrouvot** [comment]
Hello,

Thanks for your interest.
PGSENTINEL should be released officialy before mid-2019.

Thanks
Bertrand

**Comment by bdrouvot** [comment]
We can consider the current version as stabilized.
