### ISSUE TITLE
Make command failing

### ISSUE THREAD

**Issue by fkhalid28** [pgsentinel/pgsentinel#23]
Hi,
I am trying to install pgsentinel and while trying to run the make command, I am getting following errors.

# make
gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o pgsentinel.o pgsentinel.c
pgsentinel.c:19:33: fatal error: postmaster/bgworker.h: No such file or directory
 #include "postmaster/bgworker.h"
                                 ^
compilation terminated.
make: *** [pgsentinel.o] Error 1

Following is the OS details
[root@ip-172-31-58-124 10]# uname -a
Linux ip-172-31-58-124.ec2.internal 3.10.0-957.el7.x86_64 #1 SMP Thu Oct 4 20:48:51 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bdrouvot** [comment]
Hi,

Do you have development package of PostgreSQL installed or did you built PostgreSQL from source?

**Comment by fkhalid28** [comment]
Hi, I used packaged Postgres for installation

**Comment by bdrouvot** [comment]
please build PostgreSQL from source to be able to launch the make command successfully (looks like bgworker.h is not part of postgresql-devel.x86_64)
