### ISSUE TITLE
Problem with make install in alpine

### ISSUE THREAD

**Issue by iolbr** [pgsentinel/pgsentinel#27]
Hi, trying to compile pg_sentinel inside docker image based on postgres:10.7-alpine.
Did install alpine build-base and postgresql-dev. Compilation succeeds. Make install failed 
stating a missing scripts directory.
I created the missing directory and copied the sql file to it.

But make install fails with

gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -fPIC -I. -I./ -I/usr/local/include/postgresql/server -I/usr/local/include/postgresql/internal  -D_GNU_SOURCE -I/usr/include/libxml2   -c -o pgsentinel.o pgsentinel.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -fPIC -shared -o pgsentinel.so pgsentinel.o  -L/usr/local/lib   -L/lib  -L/usr/local/lib -Wl,--as-needed -lm
/bin/mkdir -p '/usr/local/lib/postgresql'
/bin/mkdir -p '/usr/local/share/postgresql/extension'
/bin/mkdir -p '/usr/local/share/postgresql/extension'
/bin/mkdir -p '/usr/local/bin'
/usr/bin/install -c -m 755  pgsentinel.so '/usr/local/lib/postgresql/pgsentinel.so'
/usr/bin/install -c -m 644 .//pgsentinel.control '/usr/local/share/postgresql/extension/'
/usr/bin/install -c -m 644 .//pgsentinel--1.0b.sql  '/usr/local/share/postgresql/extension/'
/usr/bin/install -c -m 755 .///scripts '/usr/local/bin/'
**install:** omitting directory './//scripts'**
make: *** [/usr/local/lib/postgresql/pgxs/src/makefiles/pgxs.mk:132: install] Error 1

Best,
Ingo

**Comment by bdrouvot** [comment]
Hi,

Could you please share your dockerfile? 
The one in this directory is working fine: https://github.com/pgsentinel/docker_for_testing

Bertrand

**Comment by iolbr** [comment]
Hi Bertand,

thanks for verifyfing. Did another test run today with small modifications (removed the project parts from the dockerfile) and the error went away. Will ivestigate our project parts.

Ingo
