### ISSUE TITLE
pgsentinel in a posgresql container

### ISSUE THREAD

**Issue by TamarNR** [pgsentinel/pgsentinel#30]
Hi,

I am running postgres in a container.
I added pgsentinel as an extension toshared_preload_libraries (as my postgresql.conf is mapped as a volume):
shared_preload_libraries = 'pg_stat_statements,pgsentinel'

When I try to restart the container after that, I get this error:
[1]: [1-1] FATAL:  could not access file "pgsentinel": No such file or directory

How can I set it up then pgsentinel in a container?
Or did I miss something?

Thanks,
Tamar

**Comment by TamarNR** [comment]
OK, resolved some of my issues, and now I can create the pgsentinel extension.
However, the pgsentinels table pg_active_session_history is empty.

In 'show_all' I see that:

 pgsentinel.db_name                     | postgres                                     | Database on which the worker connect.

however, I do not have such a database, instead i am using another database for my application - could that be the problem?

In addition, pg_stat_Statements table (which has almost 2000 rows) is owned by a schema which is not public.

Does pgsentinel supports this configuration?

Thanks,
Tamar

**Comment by bdrouvot** [comment]
It may be empty because not active sessions have been sampled. You can launch "select pg_sleep(120);" wait until it finishes and it should appears in  pg_active_session_history.

As far the non existing database, you should then see in the posgresql logfile messages like:
```
2021-01-23 09:31:09.812 UTC [4568] LOG:  starting bgworker pgsentinel
2021-01-23 09:31:09.812 UTC [4568] FATAL:  database "doesnotexist" does not exist
```

**Comment by TamarNR** [comment]
Hi,

Thanks for the answer.
Postgres logs indeed show this:

```
2021-01-24 14:34:19.097 IST [32] LOG:  starting bgworker pgsentinel
2021-01-24 14:34:19.097 IST [32] FATAL:  database "postgres" does not exist

```
Indeed I have no database name 'postgres' as we have our own database defined for our application.

Can pgsentinel be configured to look for another database?

Thanks,
Tamar

**Comment by bdrouvot** [comment]
yes, you have to set pgsentinel.db_name in the posgresql.conf file to a value that match an existing database.

**Comment by TamarNR** [comment]
Thanks! that worked.
