### ISSUE TITLE
Support - Installation of pgSentinel in managed Postgres

### ISSUE THREAD

**Issue by auror** [pgsentinel/pgsentinel#32]
Hi Team,

We're using managed Postgres instances on versions 11, 12 & 13 which unfortunately doesn't allow us to add a shared preloaded library when we wanted to add `pgSentinel`

Is there a way to integrate pgSentinel in this scenario ?

Thanks

**Comment by bdrouvot** [comment]
Hi,

No, it does need to be added to the ```shared_preload_libraries```.
Out of curiosity, which managed service provider are you talking about?

Bertrand

**Comment by auror** [comment]
Hi @bdrouvot 

That's great. How do we integrate pgSentinel then ? Also, it's Cloud SQL

Regards

**Comment by bdrouvot** [comment]
It needs to be added to the `shared_preload_libraries`, so if you can't modify it then you can't use pgsentinel (as any other extensions that would need a change to `shared_preload_libraries`)

**Comment by auror** [comment]
Yeah. Thanks
