### ISSUE TITLE
not enough shared memory increasing track_activity_query_size to 64K

### ISSUE THREAD

**Issue by alberto-dellera** [pgsentinel/pgsentinel#33]
I have tried to increase the max query size to cope with long, DWH-style queries: 

`track_activity_query_size = 65536 `

but I get, on cluster restart:

`waiting for server to start....:  not enough shared memory for data structure "Ash Entry Query Buffer" (65536000 bytes requested)`

on two different machines that should have plenty of memory available; e.g. one is a Linux Red Hat system with 32G memory, 20G of which is free. 

I'm not familiar at all with PG development, but could it be because in ash_shmem_startup() there are 3 shared memory requests sized after pgstat_track_activity_query_size ("Ash Entry Query Buffer", "Ash Entry Top Level Query Buffer", "Proc Query Buffer"), and only 2 corresponding in ash_entry_memsize() - probably missing "Proc Query Buffer"? 

Postgres 13.2 with latest pg_sentinel v1.0.0.

**Comment by bdrouvot** [comment]
Thanks for reaching out.
The "Proc Query Buffer" part is done in `proc_entry_memsize()` which is in `get_parsedinfo.c`.
Will have a look.

**Comment by bdrouvot** [comment]
Solved in commit 7fe711f

**Comment by alberto-dellera** [comment]
Many thanks!
