### ISSUE TITLE
make failing 

### ISSUE THREAD

**Issue by sunilbhu** [pgsentinel/pgsentinel#35]
Hi,

Make is failing with below error
"
make: /opt/rh/llvm-toolset-7/root/usr/bin/clang: Command not found
make: *** [pgsentinel.bc] Error 127
"

May I know what all packages are required to install ? I am testing OEL server. 

One more question , Can we change number of entries and retention in ASH view ?

**Comment by bdrouvot** [comment]
Hi,

The packages required to install PostgreSQL from source are documented here: https://wiki.postgresql.org/wiki/Compile_and_Install_from_source_code.

If you don't need llvm you can try with `with_llvm=no`.

To change the default number of entries, use the `pgsentinel_ash.max_entries` GUC parameter (as described in the README).
The retention is based on the number of entries only.
Bertrand

**Comment by sunilbhu** [comment]
Thanks for the reply. We install Postgres as  package on server. 

Though I installed clang through( yum install clang-devel.x86_64) , but still it is failing with same error
make
/opt/rh/llvm-toolset-7/root/usr/bin/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -O2  -I. -I./ -I/usr/pgsql-11/include/server -I/usr/pgsql-11/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -flto=thin -emit-llvm -c -o pgsentinel.bc pgsentinel.c
make: /opt/rh/llvm-toolset-7/root/usr/bin/clang: Command not found
make: *** [pgsentinel.bc] Error 127


It's trying to access clang from a different dir.(/opt/rh/llvm-toolset-7/root/)

$ which clang
/usr/bin/clang

Is it fine to follow same method as mentioned in "https://blog.dbi-services.com/pgsentinel-the-sampling-approach-for-postgresql/"

i.e.
cp pgsentinel.control /usr/pgsql-10/share/extension
cp pgsentinel--1.0.sql /usr/pgsql-10/share/extension
cp pgsentinel.so /usr/pgsql-10/lib
and declare it in postgresql.conf

$PGDATA/postgresql.conf
 
shared_preload_libraries = 'pg_stat_statements,pgsentinel'
#pgsentinel_ash.pull_frequency = 1
#pgsentinel_ash.max_entries = 1000000

**Comment by bdrouvot** [comment]
can you try to ```yum install llvm-toolset-7-clang```?
