### ISSUE TITLE
Search slow queries

### ISSUE THREAD

**Issue by Guzya** [pgsentinel/pgsentinel#36]
Hi!
I have one question.
Is it possible to search for slow queries using the pg_active_session_history table?

**Comment by bdrouvot** [comment]
Hi,
you could see the ones that are sampled frequently and you would need to compare the `query_start` field.
For example, say you see one session running the exact same query during 120 seconds (means 120 samples with sampling frequency of one second) in `pg_active_session_history`. Then comparing the `query_start` field of those samples would tell you if they are coming from the same execution or not. 
If you are looking for more insights about their executions then you can look at the `pg_stat_statements`extension.
