### ISSUE TITLE
ash_time < xact_start

### ISSUE THREAD

**Issue by vladius1972** [pgsentinel/pgsentinel#37]
Sometimes the values of the ash_time is less than xact_start or query_start. In my opinion this is incorrect. For example, in oracle-db in a similar v$active_session_history, sample_time is always greater than or equal to the query start time (sql_exec_start). 
It is possible to get it from the database simultaneously with the pg_stat_activity data?

**Comment by bdrouvot** [comment]
I think i know where it comes from. Can you please confirm or not that when it happens the difference between the ash_time and query_start is <= 1 second (sampling interval).

**Comment by vladius1972** [comment]
ash_time difference:
```sql
select min(query_start-ash_time) min_qry_ash_dif
,max(query_start-ash_time) max_qry_ash_dif
,min(xact_start-ash_time) min_xact_ash_dif
,max(xact_start-ash_time) max_xact_ash_dif
from public.pg_active_session_history ash 
where ash_time<xact_start;
```
min_qry_ash_dif|max_qry_ash_dif|min_xact_ash_dif|max_xact_ash_dif|
---------------|---------------|----------------|----------------|
00:00:00.029176|00:00:01.003396| 00:00:00.029176| 00:00:01.003347|

snapshot accuracy:
```sql
with ash as (
select ash_time, lag(ash_time) over(order by ash_time) ash_prev
from (select distinct ash_time from public.pg_active_session_history) gg
)
select min(ash_time-ash_prev) min_time_dif, max(ash_time-ash_prev) max_time_dif
from ash;
```
min_time_dif|max_time_dif
--------------|----------------
00:00:01.001783|00:00:01.013304

**Comment by bdrouvot** [comment]
Thanks for the report. Last commit should fix this behavior.
