### ISSUE TITLE
multiple definition of `ProcEntryArray' and prev_post_parse_analyze_hook

### ISSUE THREAD

**Issue by anilbommareddy** [pgsentinel/pgsentinel#40]
PostgreSQLv14 source code compiled and install with GCCv11.1.
Installed Path:/usr/local/postgres_14/gcc/bin(pg_config)
OS:RHEL8.4

Steps are followed:
export PATH=/usr/local/gcc-11/bin:/usr/local/postgres_14/gcc/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/gcc-11/lib:/usr/local/gcc-11/lib64:$LD_LIBRARY_PATH
git clone https://github.com/pgsentinel/pgsentinel.git
$ cd pgsentinel/src
$ make
  -Wl,--as-needed -Wl,-rpath,'/usr/local/postgres_14/gcc/lib',--enable-new-dtags -lm
get_parsedinfo.o:(.bss+0x8): multiple definition of `prev_post_parse_analyze_hook'
pgsentinel.o:(.bss+0x8): first defined here
get_parsedinfo.o:(.bss+0x0): multiple definition of `ProcEntryArray'
pgsentinel.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make: *** [/usr/local/postgres_14/gcc/lib/pgxs/src/makefiles/../../src/Makefile.shlib:293: pgsentinel.so] Error 1

**Comment by bdrouvot** [comment]
can you give it a try, adding
```
PG_CFLAGS=-fcommon
```
in the extension Makefile? (before PG_CONFIG = pg_config)

Thanks
Bertrand

**Comment by bdrouvot** [comment]
recent gcc versions have  default to -fno-common producing the errors mentioned in this issue.
Temporary workaround can be to set 
```
PG_CFLAGS=-fcommon
```
in the extension Makefile.

In the same time, I'm doing minor code changes to avoid such errors even with fno-common.

Thanks
Bertrand

**Comment by bdrouvot** [comment]
Fixed in https://github.com/pgsentinel/pgsentinel/commit/eb7125265cd7dbc32150dd78648bbfcfd40660bf

Thanks
Bertrand

**Comment by einisadog** [comment]
> 

Thanks for the optimazation, I meet the same problem.
