### ISSUE TITLE
cannot create PGC_POSTMASTER variables after startup

### ISSUE THREAD

**Issue by yuanduobin** [pgsentinel/pgsentinel#42]
postgresql  version 14.5 error
testdb=# create extension pgsentinel;
FATAL:  cannot create PGC_POSTMASTER variables after startup
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.

**Comment by bdrouvot** [comment]
It's likely that you are getting the error because `pgsentinel` is not part of `shared_preload_libraries` on your cluster (while it should).

To avoid this error, 014e031ccfe51281a9d3a6331ef28fdcbc927ced has been pushed.
