### ISSUE TITLE
Make failing with get_parsedinfo.o - too few arguements

### ISSUE THREAD

**Issue by r-chauhan16** [pgsentinel/pgsentinel#45]
Hi,

I am trying to compile pgsentinel from source. PGVERSION is 14. OS - RHEL 7

[root@hostname src]# env|grep PATH
PATH=/usr/pgsql-14/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin

[root@hostname src]# make
gcc -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -fPIC -I. -I./ -I/usr/pgsql-14/include/server -I/usr/pgsql-14/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o pgsentinel.o pgsentinel.c
pgsentinel.c: In function ‘_PG_init’:
pgsentinel.c:1407:26: warning: assignment from incompatible pointer type [enabled by default]
  post_parse_analyze_hook = getparsedinfo_post_parse_analyze;
                          ^
gcc -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -fPIC -I. -I./ -I/usr/pgsql-14/include/server -I/usr/pgsql-14/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o get_parsedinfo.o get_parsedinfo.c
get_parsedinfo.c: In function ‘getparsedinfo_post_parse_analyze’:
get_parsedinfo.c:85:3: error: too few arguments to function ‘prev_post_parse_analyze_hook’
   prev_post_parse_analyze_hook(pstate, query);
   ^
make: *** [get_parsedinfo.o] Error 1

Can you help what is wrong?

Regards,
Ravi

**Comment by bdrouvot** [comment]
Are you using a recent version of pgsentinel? Asking as the current code deals with this in get_parsedinfo.c:
```
#if PG_VERSION_NUM < 140000
        prev_post_parse_analyze_hook(pstate, query);
#else
        prev_post_parse_analyze_hook(pstate, query, jstate);
#endif
```

**Comment by r-chauhan16** [comment]
Yes, I am using the recent version, downloading from github.

**Comment by bdrouvot** [comment]
So it looks like that your environment is returning PG_VERSION_NUM < 140000

**Comment by r-chauhan16** [comment]
Do I have to set it manually or what needs to be done here.
