### ISSUE TITLE
condition monitoring - idle in transaction

### ISSUE THREAD

**Issue by sgrinko** [pgsentinel/pgsentinel#8]
Please add session status tracking - 'idle in transaction'.

session in the status of 'idle in transaction' - keeps the locks open in it.
Therefore, it interferes with the work of vacuum and the work of other sessions, which results in bloat in tables and timeout in other client requests.
Therefore, such sessions should be carefully monitored and dealt with the causes leading to their occurrence.
Also it's wasted spending of such a valuable resource as connect to the server (this is very important for pooling).

**Comment by bdrouvot** [comment]
In progress: will be merged in the same time as issue #13 (Add blocked_by session(s)) as they are somehow related.

**Comment by sgrinko** [comment]
Thank you!

**Comment by bdrouvot** [comment]
In fact, it's somehow weird to collect non active session. The same on oracle: a blocking session not active does not appear in ash. With the new merge, we now have the (one of the) blocker(s).

**Comment by sgrinko** [comment]
I do not understand how the numbers collection of blocking sessions will help me ...
Oracle - can not in this case be an indicator!
We have another model of data storage and a session in a state of `idle in transaction` leads to disaster. In Oracle this is not! 
I need to know when `idle in transaction` it started and see the problem in history.
Please add.

**Comment by bdrouvot** [comment]
let's do it an other way: add info about blocker(s) into new columns (say: blockerstate, blockerquery). So that we record blocker(s) informations and still collect only active session. Sounds good?

**Comment by sgrinko** [comment]
add info `blockerstate` it's a good idea.
However, the connection in this status ' idle in transaction` does not prevent to do insert and delete in the involved transaction tables, but prevents autovacuum from working, which leads to bloat. 
Therefore, in the current scenario, we will never see a session with the status `idle in transaction`among the blocked sessions.
I need to be able to track the start time of such connections to take action to address them.
Of course, I could keep track of myself at some time interval for such compounds, but in this case, I'm going to `reinvent the wheel`.
If you implement the parameter `tracking_idle_in_transaction` ? This will allow those who do not need to not see such sessions in history.

**Comment by bdrouvot** [comment]
Implemented: see commit a5301acfb89bf1b4af52a1d922d5adb05bd113dd
